{
 "title": "eth-miner panel",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "大盘一览总数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "summary",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "掉线",
   "type": "singlestat",
   "description": "过去十分钟掉线的矿机",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "summary",
     "query": "select count(distinct(\"name\")) from (SELECT \"15_hash\", \"name\" FROM \"miner\" WHERE (time >= now() - 6h ) and (\"15_hash\"<20))",
     "select": [
      [
       { "params": [ "lost" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU监控",
   "type": "briangann-datatable-panel",
   "description": "GPU数目检测",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "miner",
     "query": "SELECT \"GPU\", \"detectedGPU\" FROM \"miner\" WHERE (\"detectedGPU\" < GPU) AND $timeFilter GROUP BY \"name\", \"teamview\"",
     "select": [
      [
       { "params": [ "GPU" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "配置的GPU数目" ], "type": "alias" }
      ],
      [
       { "params": [ "detectedGPU" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "检测到的GPU数目" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "GPUFailed", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "矿机工作监控",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "teamview" ], "type": "tag" },
      { "params": [ "wallet" ], "type": "tag" }
     ],
     "measurement": "miner",
     "query": "SELECT last(\"2_hash\") AS \"２分钟\", last(\"15_hash\") AS \"１５分钟\", last(\"60_hash\") AS \"一小时\" FROM \"miner\" WHERE $timeFilter GROUP BY \"name\", \"teamview\", \"wallet\"",
     "select": [
      [
       { "params": [ "2_hash" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "２分钟" ], "type": "alias" }
      ],
      [
       { "params": [ "15_hash" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "１５分钟" ], "type": "alias" }
      ],
      [
       { "params": [ "60_hash" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "一小时" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}